package:
  name: petsc
  version: 3.6.2+mapdes

source:
  fn: petsc-lite-3.6.2.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.6.2.tar.gz
  md5: 5b6b7129ba02f4c6d107ae7671b80bb8

build:
  number: 1
  rpaths:
    - lib/python{{environ['PY_VER']}}/site-packages/petsc/lib
    - lib

requirements:
  build:
    - python
    - openblas
    - mpi4py
    - gcc

  run:
    - python
    - openblas
    - mpi4py
    - libgcc

test:
  requires:
    - gcc

about:
  home: http://www.firedrakeproject.org
  license: BSD
  summary: PETSc from the Firedrake Project's repository
