package:
  name: petsc4py
  version: 3.6.0+mapdes

source:
  fn: petsc4py-3.6.0.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-3.6.0.tar.gz
  md5: e63a8e30318b5de9ffb081832e9daf30

build:
  number: 1
  rpaths:
    - lib/python{{environ['PY_VER']}}/site-packages/petsc/lib
    - lib

requirements:
  build:
    - python
    - openblas
    - numpy ==1.9
    - petsc ==3.6.2+mapdes

  run:
    - python
    - openblas
    - numpy ==1.9
    - petsc ==3.6.2+mapdes

test:
  imports:
    - petsc4py
    - petsc4py.lib

about:
  home: http://www.firedrakeproject.org
  license: BSD
  summary: PETSc4py from the Firedrake Project's repository
