package:
  name: firedrake
  version: "0.12.0"

source:
  git_url: https://github.com/firedrakeproject/firedrake
  git_tag: v0.12.0
  patches:
    - 0001-Remove-del-petsc-from-__init__.py.patch

requirements:
  build:
    - python
    - numpy
    - cython
    - petsc4py ==3.6.0+mapdes
    - h5py
    - libspatialindex

  run:
    - python
    - numpy
    - h5py
    - libspatialindex
    - ufl ==1.5.0+mapdes
    - fiat ==1.5.0+mapdes
    - instant ==1.5.0+mapdes
    - ffc ==1.5.0+mapdes
    - pyop2

test:
  requires:
    - pytest

about:
  home: http://firedrakeproject.org/
  summary: 'The Firedrake System for Automated Solution of PDEs using FEM'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
